enum actionTypes {
  SUBS_LOAD = "SUBS_LOAD",
  SUBS_ADD = "SUBS_ADD",
  SUBS_REMOVE = "SUBS_REMOVE",
  AUTH_SET = "AUTH_SET",
  AUTH_CLEAR = "AUTH_CLEAR",
  FETCH_REQUEST = "FETCH_REQUEST",
  FETCH_SUCCESS = "FETCH_SUCCESS",
  FETCH_FAILURE = "FETCH_FAILURE",
  CACHE_SET = "CACHE_SET",
  VIEW_TOGGLE_SIDEBAR = "VIEW_TOGGLE_SIDEBAR",
  VIEW_CHANGE_THEME = "VIEW_CHANGE_THEME",
}

export default actionTypes;
